language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  cargo: true
  directories:
    - "$HOME/.rustup"
  branch: "joshk/reduce-compression"

before_cache:
  - rm -rf "$HOME/.cargo/registry/src"

before_script:
  - rustfmt --help 2>/dev/null >/dev/null || rustup component add rustfmt
  - cargo-clippy --help 2>/dev/null >/dev/null || rustup component add clippy || true

script:
  - cargo build --all
  - cargo test --all
  - cargo fmt --all -- --check
  - cargo clippy --help 2>/dev/null >/dev/null && cargo clippy --all --tests -- -D clippy::all
